version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing dependencies...
      - npm install -g @angular/cli
      - npm install

  build:
    commands:
      - echo Building the Angular app...
      - ng build --prod

artifacts:
  files:
    - '**/*'
  base-directory: dist